name: C/C++ CI Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build & run ubuntu
      run: |
        cmake -H. -B_build -DCMAKE_BUILD_TYPE=Release
        cmake --build _build --config Release
        for files in "_build/Day*/Day*"
        do
          for file in $files
          do
            echo $file
            ./$file
          done
        done
