name: C/C++ CI macOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  generate:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: build & run
      run: cmake -H. -B_build -DCMAKE_BUILD_TYPE=Release
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: build & run
      run: cmake --build _build --config Release
  run:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: build & run
      run: |
        for files in "_build/Day*/Day*"
        do
          for file in $files
          do
            echo $file
            ./$file
          done
        done
